name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ libeigen3-dev libboost-all-dev

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ./test_newton
          ./test_bisection
